#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server


path_to_file='$1'
ip='#2'
username='$3'
path_to_ssh_key='$4'


if [ $# -lt 3 ]; then
        echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no $path_to_file $username@$ip:~/
else
	scp -i $path_to_ssh_key -o StrictHostKeyChecking=no $path_to_file $username@$ip:~/
fi
