#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server

if [$# -lt 3]; then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1
fi

path_to_file='$1'
ip='#2'
username='$3'
path_to_ssh_key='$4'

ssh_options="-o StrictHostKeyChecking=no"

# Construct the destination path on the server
destination_path="~"

# Check if a custom path to SSH private key is provided
if [ -n "$path_to_ssh_key" ]; then
    scp_cmd="scp -i $path_to_ssh_key $ssh_options $path_to_file $username@$ip:$destination_path"
else
    scp_cmd="scp $ssh_options $path_to_file $username@$ip:$destination_path"
fi

# Execute the SCP command
echo "Transferring file..."
$scp_cmd

if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error transferring file."
fi
