#!/usr/bin/env bash
#Script to configure server to redirect

# Update package list
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Create a new server block configuration file for redirection
sudo tee /etc/nginx/sites-available/redirect_config <<EOF
server {
    listen 80;
    server_name blackpivot.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # You can add other configurations for your domain here

    # Include other server blocks if needed
}
EOF

# Create a symbolic link to enable the new server block
sudo ln -s /etc/nginx/sites-available/redirect_config /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo /etc/init.d/nginx reload
