#!/usr/bin/env bash
#installing and configuring HAProxy for load balancing

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy=2.4.\*

new_config=\
"
backend marbet-b
        mode http
        balance roundrobin
        server 247079-web-01 52.87.154.89:80 check
        server 247079-web-02 54.174.246.6:80 check
frontend marbet-f
        bind *:80
        mode http
        default_backend marbet-b
"
echo "$new_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
