#!/usr/bin/env bash
#Script that pings an IP address passed as an argument

if [ -z "$1" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

IP="$1"
PING=$(ping -c 5 "$IP")
echo "$PING"
