#!/usr/bin/env bash
#Script to display numbers 1-20 and strings after 4th, 9th and 17th numbers

STRING="bad luck from China"
STRING1="bad luck from Japan"
STRING2="bad luck from Italy"
count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		4)
		echo "$STRING"
		;;
		9)
		echo "$STRING1"
		;;
		17)
		echo "$STRING2"
	esac
	count=$((count + 1))
done
